export const CLEAR_CART = "CLEAR_CART";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const INCREASE_AMOUNT = "INCREASE_AMOUNT";
export const DECREASE_AMOUNT = "DECREASE_AMOUNT";
export const START_FETCHING_DATA = "START_FETCHING_DATA";
export const STOP_FETCHING_DATA = "STOP_FETCHING_DATA";
export const DISPLAY_ITEMS = "DISPLAY_ITEMS";
